name: "CI"

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: 'macos-latest'

    continue-on-error: true

    strategy:
      fail-fast: true
      matrix:
        php-version:
          - '5.6'
          - '7.0'
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2.3.3

      - run: |
          set -xe

          brew --version
          brew tap shivammathur/php
          brew install shivammathur/php/php@${{ matrix.php-version }}
          ./phpln.sh ${{ matrix.php-version }}
          v1=$(php -v | grep -e '^PHP' | cut -d' ' -f2)
          phpln="php"$(php -v | grep -e '^PHP' | cut -d' ' -f2 | cut -d. -f1,2 | sed 's#\.##g')
          v2=$($phpln -v | grep -e '^PHP' | cut -d' ' -f2)
          if [ "$v1" != "$v2" ]; then
            echo "Expected $v1 got $v2 ( ${{ matrix.php-version }} )"
            exit 1
          fi
          ./phpln.sh ${{ matrix.php-version }} -m
          v1=$(php -v | grep -e '^PHP' | cut -d' ' -f2)
          switched=$(php -v | grep -e '^PHP' | cut -d' ' -f2 | cut -d. -f1)
          if [ "$v1" != "$v2" ]; then
            echo "Expected $v1 got $v2 ( ${{ matrix.php-version }} )"
            exit 1
          fi
